### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Falteri** [omeka-s-modules/UnApi#2]
UnApi module seems to not working at all, at least in my Omeka S 1.1.0 instance.
See http://engb.bmlonline.it/unapi?id=380&format=rdf_dc

**Comment by Frederic-P** [comment]
Hey (I'm not the developer of this module, but I'm looking into using it on demonstration site for a project using Omeka S).

I looked at the Response Payload of your website with Firefox Developer Edition and there you see:

```
<!DOCTYPE html><html lang="en-US">    <head>
        <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">        <title>ENGB</title>        <link href="//fonts.googleapis.com/css?family=Source+Code+Pro|Lato:400,400italic,700,700italic" media="screen" rel="stylesheet" type="text/css">
<link href="/application/asset/css/iconfonts.css?v=1.1.1" media="screen" rel="stylesheet" type="text/css">
<link href="/application/asset/css/style.css?v=1.1.1" media="screen" rel="stylesheet" type="text/css">                <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript" src="/application/asset/js/global.js?v=1.1.1"></script>    </head>
    <body class="minimal">
        <div id="content" role="main">
                        <h1>Omeka S encountered an error</h1>

        </div>
        <footer>
            <span class="powered-by">Powered by Omeka S</span>
        </footer>
    </body>
</html>

```

I had this too the first time testing the unAPI module on my localhost and it turned out that I was addressing the API from the wrong directory. For me using the following path worked: localhost/omeka/unapi?id=7&format=rdf_dc

(localhost/omeka/ is the directory containing the 'modules', 'application', 'config'... etc. subfolders.)

check if your rewrite rules don't interfere with this. If this fixes your issue, then perhaps open a new ticket to update the documentation of this module.
Good luck.

**Comment by Daniel-KM** [comment]
Can you unable the development mode to see the issue in the log (set it in the .htaccess file: https://omeka.org/s/docs/developer/key_concepts/debugging/)?

**Comment by Daniel-KM** [comment]
Note that only the authentified user can see the unapi (unless if you use my pr #1 ).
